# Generated by Django 4.1.5 on 2023-01-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("edition", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
